### ISSUE TITLE
Diff generator should provide git diff download

### ISSUE THREAD

**Issue by grantwest** [zestcreative/utility#26]
It would be very convenient to be able to download a git patch from the diff generator. I could then apply it to my repo and easily address any conflicts.

**Comment by dbernheisel** [comment]
Oh that's a great idea! It might not be effective given the default app name of `MyApp` but it's worth a try.

**Comment by grantwest** [comment]
After testing I have discovered that it does not work. Patches need a common ancestor commit to work the way I was hoping. I have built a script that upgrades a git repo assuming you made a commit right after generating the project with `mix phx.new`. After I refine it a bit I'll put it on GitHub.

**Comment by dbernheisel** [comment]
Drat. Ok, hmm. Thanks for giving it a shot
