### ISSUE TITLE
Unable to generate diff for phx_new when main is selected as version

### ISSUE THREAD

**Issue by JBraungardt** [zestcreative/utility#30]
It seems that the main branch for phoenix now requires at least elixir version 1.15
But the version used by rel/overlays/diffbuilder/Dockerfile.latest is using 1.14.1

The solution might be to update this to 15 or add an other dockerfile used by phoenix on the main branch.

**Comment by dbernheisel** [comment]
Yep. Looks like i need a new docker image to build latest. No problem!
