### ISSUE TITLE
No diff for phoenix umbrella

### ISSUE THREAD

**Issue by 6aKa** [zestcreative/utility#9]
Show without diff
 ```
VERSION=1.5.5 phx.new my_app --umbrella
VERSION=1.5.9 phx.new my_app --umbrella
```

For example:
`https://utils.zest.dev/gendiff/phx_new/8B724AA0059ECB7B0EB3EB5700862447`

**Comment by 6aKa** [comment]
up

**Comment by dbernheisel** [comment]
Sorry I missed this so long ago.

I'm able to generate diff locally between the two versions and see some diff, so I'll need to pinpoint where the issue is.

**Comment by 6aKa** [comment]
https://utils.zest.dev/gendiff/phx_new/CAD048CAD007061BBBA69DD0A674D990

**Comment by 6aKa** [comment]
go to https://utils.zest.dev/gendiff/
set `phx_new` in "Project" select
set `1.6.0` in "From Version" select
set `1.6.6` in "To Version" select
set `phx.new` in "Command" select
select `--umbrella` in "From 1.6.0 Flags"
select `--umbrella` in "From 1.6.6 Flags"
press "Get Diff" button
get blank page with next content
```
VERSION=1.6.0 phx.new my_app --umbrella
VERSION=1.6.6 phx.new my_app --umbrella
```

**Comment by dbernheisel** [comment]
Fixed now. Looks like I hard-coded the folder that is generated to be `my_app` but in the umbrella's case it was `my_app_umbrella`. All cached rendered diffs have been invalidated so please try again.
